In [ ]:
pip install jupyterlab-git

In [26]:
import pandas as pd
import numpy as np

In [27]:
# pd calls pandas, then .read_csv('csv.csv') reads the file from the folder
train_data = pd.read_csv('train.csv')

# putting .head() shows the first five values of the dataset
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [28]:
# We repeat this process for test.csv
test_data = pd.read_csv('test.csv')
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [29]:
women = train_data.loc[train_data.Sex == 'female']["Survived"]

**train_data.Sex == 'female'** -> this sorts the male and the female passengers and labels males as false and females as true\
**train_data.loc [train_data.Sex == 'female']** -> this sorts the passengers so only the rows with females remain then the **["Survived"]** at the end sorts out the people that survived\
The full line of code is 'women' is the total amount of women who survived in the titanic

In [30]:
print("Total amount of women who died on the titanic:", sum(women))

Total amount of women who died on the titanic: 233

**sum(women)** -> since the the people who survived are labeled as 1 and the people who didn't are labeled as 0, the line sums up the total amount of (1s) which counts the total amount of women who survived

In [31]:
print("Total amount of women on the titanic:", len(women))

Total amount of women on the titanic: 314

**len(women)** -> this counts the total length (or amount of women) on the titanic regardless on whether they survived or not

In [37]:
rate_women = sum(women)/len(women)
print(sum(women),"/",len(women),"=", rate_women)
print("% of women who survived:", 100 * rate_women)

233 / 314 = 0.7420382165605095
% of women who survived: 74.20382165605095

**rate_women =** -> this calculates the amount of women who survived on the titanic (sum(women) over the total amount of women on the ship, showing the survival rate of women on the titanic

In [36]:
# repeat the same process for the men on the titanic
men = train_data.loc[train_data.Sex == 'male']["Survived"]
rate_men = sum(men)/len(men)

print("% of men who survived:", 100 * rate_men)

% of men who survived: 18.890814558058924 %

Comparing the precentage of women that survived (74.20) and the percentage of men (18.89), we see that almost 75% of women survived and only 19% of men survived

In [40]:
from sklearn.ensemble import RandomForestClassifier

Imports the Random Forest classification algorithm form the scikit-learn libary

In [41]:
y = train_data["Survived"]

sets y as the model that will predict whether a passenger survived or not.

In [ ]:
features = ["Pclass", "Sex", "SibSp", "Parch"]

the columns that will be used to predict the survival (the varibles)

In [ ]:
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

**pd.get_dummies** -> transforms training data and testing data into categorical data like sex into numerical dummy varibles so the algorithm can proccess it

In [ ]:
model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)

**RandomForestClassifier()** -> initializes the random forest model\
**n_estimators = 100** -> the amount of decision trees\
**max_depth = 5** -> how deep you would want the tree to go to prevent overfitting\
**random_state = 1** -> ensure consistant, reproducable results

In [ ]:
model.fit(X, y)

trains the model by showing the training feature (X) along with the survival outcomes (y)

In [ ]:
predictions = model.predict(X_test)

**model.predict()** -> runs the model using infrences only\
The whole line of code means that we are using the testing dataset (X_test) to run and predict the outcome (predictions).

In [ ]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})

**pd.DataFrame()** -> using pandas, we create a data structure (a table) to store the output\
**test_data.PassengerId** PassengerId is found by going into the test data dataset and selecting the PassengerId feature\
**predictions** The survived is calcuated in the predictions model that was made above

In [ ]:
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

**output.to_csv()** save the output table as a csv file named $submission.csv$

In [44]:
submission = pd.read_csv('submission.csv')
submission

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]